config/routes.rb
Rails.application.routes.draw do
  root "trips#index"

  devise_for :users 
  
  resources :users, only: [:show] do 
    resources :trips, except: [:index, :show, :edit]
  end

  resources :trips, only: [:show, :index, :create, :edit, :update] do
    resources :locations, except: [:index, :show]
  end
  
  resources :locations, only: [] do
    resources :addresses, except: [:index, :show]
  end

  # create"locations/:location_id/adresses" => "addresses#create"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip
  has_one :address, dependent: :destroy
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trips, dependent: :destroy
  def full_name
    first_name +  " " + last_name
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  
    before_action :set_location
    before_action :set_address, only: [:show, :edit, :update, :destroy]
  
    def index
      @addresses = @location.addresses.all
    end
  
    def show
      
    end
  
    def new
      @address = Address.new()
      render partial: "form"
    end
  
    def create
      @address = Address.new(
        street_address: params[:street_address],
        location_id: @location.id,
      )
      if @address.save
        redirect_to trip_path(@location.trip.id)
      else
        render :new
      end
    end
  
    def edit
      render partial: "form"
    end
  
    def update
      if @address.update(address_params)
        redirect_to trip_path(@location.trip.id)
      else
        render :edit
      end
    end
  
    def destroy
      @address.destroy
      redirect_to @trip
    end
  
    private
      def address_params
        params.require(:address).permit(:street_address)
      end
  
      def set_address
        @address = Address.find(params[:id])
      end
  
      def set_location
        @location = Location.find(params[:location_id])
      end
  end
  
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
    end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip
  before_action :set_location, only:[:edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @location = Location.new
    # @trip = Trip.find(params[:id])
  end

  def create
    @location = @trip.locations.new(location_params)

    if @location.save
      redirect_to @trip
    else
      render partial: "form"
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to @trip
    else
      render partial: "form"
    end
  end

  def destroy
    @location.destroy
    redirect_to @trip
  end

  private
    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:city, :state, :country)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, except: [:index, :new, :create]

  def index
    @trips = current_user.trips
  end

  def show
  end

  def new
    @trip = current_user.trips.new
    render partial: "form"
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.save
      redirect_to trips_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private

    def set_trip
      @trip = current_user.trips.find(params[:id])
    end

    def trip_params
      params.require(:trip).permit(:name)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<h1><%= @address.id ? "Edit Address" : "New Address" %></h1>
<hr />
<%= form_for [@location, @address] do |f| %>
  <%= f.label :address %>
  <%= f.text_field :street_address, autofocus: true %>
 
  <%= f.submit %>
<% end%>

app/views/addresses/edit.html.erb
<h1>Addresses#edit</h1>
<p>Find me in app/views/addresses/edit.html.erb</p>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>

app/views/addresses/new.html.erb
<h1>Addresses#new</h1>
<p>Find me in app/views/addresses/new.html.erb</p>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="navbar">
    <div class="navbar__left">
        <p class="navbar__heading"> Trip Tracker </p>
        <% if @trip %>
            <%= link_to "Add Location", new_trip_location_path(@trip.id), class: "navbar__add-location" %>
        <% end %>
    </div>


    <% if @trip %>
        <div class="navbar__trip">
            <%= @trip.name %>
        </div>
    <% end %>

    <div class="navbar__right">
        <% if current_user %>
            <a href="/trips">
                <div class="navbar__user">
                    <p class= "navbar__user-name" > <%= current_user.first_name %> </p>
                    <img class="navbar__user-avatar" src="<%= current_user.avatar %>" ></img>
                </div>
                </a>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackathon1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render "layouts/navbar" %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<h1><%= @location.id ? 'Edit Location' : 'Add a Location' %></h1>
<hr />

<% if @location.id %>
  <%= form_for @location, url: "/trips/#{@trip.id}/locations/#{@location.id}", method: :put do |f| %>
    <div class="form-control">
      <%= f.label :city %>
      <%= f.text_field :city, placeholder: "City" %>
    </div>
    <div class="form-control">
      <%= f.label :state %>
      <%= f.text_field :state, placeholder: "State/Province" %>
    </div>
    <div class="form-control">
      <%= f.label :country %>
      <%= f.text_field :country, placeholder: "Country" %>
    </div>
    <%= f.submit %>
  <% end %>
  

<% else %>
  <%= form_for @location, url: "/trips/#{@trip.id}/locations", method: :post  do |f| %>
  <div class="form-control">
      <%= f.label :city %>
      <%= f.text_field :city, placeholder: "City" %>
    </div>
    <div class="form-control">
      <%= f.label :state %>
      <%= f.text_field :state, placeholder: "State/Province" %>
    </div>
    <div class="form-control">
      <%= f.label :country %>
      <%= f.text_field :country, placeholder: "Country" %>
    </div>
    <%= f.submit %>
  <% end %>

<% end %>

app/views/locations/edit.html.erb
<%= render 'form', trip: @trip, location: @location %>
<%= link_to 'Back', trip_locations_path(@trip) %>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>

app/views/locations/new.html.erb
<%= render "form" %> 
<%= link_to 'Back', trips_path(@trip) %>

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>

app/views/trips/_form.html.erb
<%= form_for @trip , method: :post do |f| %>
  <%= f.label :name, required: true %>
  <br />
  <%= f.text_field :name %>
  <br />
  
  <%= f.submit %>

<% end %>

app/views/trips/edit.html.erb
<h1>Edit Trip: <%= @trip.name %></h1>
<%= form_for @trip do |f| %>
  <%= f.label :name, required: true %>
  <br />
  <%= f.text_field :name %>
  <br />
  
  <%= f.submit %>

<% end %>

app/views/trips/index.html.erb
<h1>Trip Tracker for <%= current_user.full_name %></h1>
<br />
<div class='trip-index'>
<% @trips.each do |trip| %>
  <ul class="list-group">
    <li class="list-group-item"><%= link_to trip.name, trip_path(trip), class: 'trip-index'%></li>
  </ul>  
<% end %>
</div>
<%= button_to 'Add Trip', new_user_trip_path(current_user), method: :get, class: "btn btn-outline-primary" %>
<%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>

app/views/trips/new.html.erb
<h1>Add Trip</h1>

<%= render 'form' %>

app/views/trips/show.html.erb
<%# <div class="wallpaper" style="background-image: url(/assets/mountain.jpg);" >
</div> %>

<h1 class="trip-location">Locations On Trip</h1>
<%= link_to 'Edit Trip', edit_trip_path(@trip) %>
<%= link_to 'Delete Trip', [current_user, @trip], method: :delete %>

<% @trip.locations.each() do |location| %>
    <div class="show__location">
        <p> Location: <%= location.city %>  <%= link_to "Edit", edit_trip_location_path(@trip.id, location.id)  %> </p>
        <p> Address: <%= location.address.street_address %> <%= link_to "Edit", edit_location_address_path(location.id, location.address.id)  %> </p>
        <%= link_to "Add Address", new_location_address_path(location.id) %>
    </div>
<% end %>